FROM nvcr.io/nvidia/l4t-base:r32.5.0

LABEL maintainer="Sean Vig <sean.v.775@gmail.com>"

COPY jetson-ota-public.asc /etc/apt/trusted.gpg.d/jetson-ota-public.asc
RUN  apt-get update \
  && apt-get install -y --no-install-recommends \
         ca-certificates \
  && echo "deb https://repo.download.nvidia.com/jetson/common r32.5 main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list \
  && echo "deb https://repo.download.nvidia.com/jetson/t186 r32.5 main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
         cuda-command-line-tools-10-2 \
         cuda-compiler-10-2 \
         cuda-libraries-dev-10-2 \
         cuda-nvml-dev-10-2 \
         cuda-nvrtc-dev-10-2 \
         cuda-nvtx-10-2 \
         python3-dev \
         python3-libnvinfer-dev \
         tensorrt \
  && ln -sf python3 /usr/bin/python \
  && rm -rf /var/cache/apt /var/lib/apt/lists/*
