FROM nodered/node-red-docker:0.18.4-slim-v8

LABEL description="Node red container with home assistant nodes" \
      maintainer="sean.v.775@gmail.com"

RUN npm install node-red-contrib-home-assistant@0.3.0
