homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York

automation: !include_dir_merge_list automations/
group: !include groups.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    #filter:
    #  include_domains:
    #    - camera
    #    - group
    #    - scene
    #    - switch
    #  include_entities:
    #    - binary_sensor.sensor
    #    - binary_sensor.sensor_2
    #    - binary_sensor.sensor_3
    #    - binary_sensor.sensor_4

#amcrest_nvr:
#  - name: NVR
#    host: !secret amcrest_url
#    username: !secret amcrest_user
#    password: !secret amcrest_pass
#    binary_sensors: [online]
#    sensors: [sdcard]
#    cameras:
#      - name: Front Porch
#        channel: 0
#        stream_source: rtsp
#        binary_sensors: [motion_detected]

#config:

cover:
  - platform: group
    name: Living Room
    unique_id: living_room_shade_group
    entities:
      - cover.living_room_left_shade
      - cover.living_room_conter_shade
      - cover.living_room_right_shade
      - cover.living_room_side_shade
  - platform: group
    name: Dining Room
    unique_id: dining_room_shade_group
    entities:
      - cover.dining_room_left_shade
      - cover.dining_room_right_shade
  - platform: group
    name: Office
    unique_id: office_shade_group
    entities:
      - cover.office_left_shade
      - cover.office_right_shade
      - cover.office_side_shade
  - platform: group
    name: Master Bedroom
    unique_id: master_bedroom_shade_group
    entities:
      - cover.master_bedroom_left_shade
      - cover.master_bedroom_right_shade
      - cover.master_bedroom_side_shade

#conversation:

default_config:

#device_tracker:

#discovery:

#ecobee:
#  api_key: !secret ecobee_api_key

#frontend:

#group:
#  first_floor:
#    name: First Floor
#    entities:
#      - media_player.living_room_tv
#      - switch.dining_room
#      - switch.hall
#      - switch.kitchen
#      - switch.living_room
#  second_floor:
#    name: Second Floor
#    entities:
#      - switch.office
#      - switch.upstairs

#history:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.110.1

#input_boolean:
#  vacation:
#    name: Vacation
#    icon: mdi:airplane

#logbook:

#logger:
#  default: info

#map:

#media_player:

# enable the mobile app support
#mobile_app:

#panel_iframe:
#  nodered:
#    title: "Node-Red"
#    icon: mdi:shuffle-variant
#    url: !secret nodered_url

#person:

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30

#script: !include scripts.yaml

#sensor:


#sonos:
#  media_player:
#    hosts:
#      - 10.10.10.58
#    advertise_addr: 10.10.10.2

#stream:

#sun:

#system_health:

#tts:
#  - platform: google_translate
#    service_name: google_say

#updater:

#zeroconf:

#zone:

#zoneminder:
#  host: !secret zoneminder_url
#  username: admin
#  password: !secret zoneminder_pass
#  ssl: true

#zwave:
#  usb_path: /dev/zwave
#  network_key: !secret zwave_key
