homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  currency: USD
  country: US

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_domains:
        - "light"
      include_entities:
        - "fan.living_room_fan"
        - "switch.front_porch_plugs"
        - "switch.printer_plug"
        - "switch.christmas_tree_plug"
        - "media_player.living_room_tv"
        - "media_player.shield_2"
      include_entity_globs:
        - "cover.*_shade"
        - "input_boolean.alexa_*_occupancy"
      exclude_entities:
        - "light.christmas_tree_plug_light"
        - "light.doorbell_led"
        # - "light.hatch_light"
        - "light.washer_plug_light"
        - "light.d3_led"
        - "light.d3_led_2"
        - "light.airgradient_open_air_status_led"
      exclude_entity_globs:
        - "light.*_follower"
        - "light.*_follower_*"

    #filter:
    #  include_domains:
    #    - camera
    #    - group
    #    - scene
    #    - switch
    #  include_entities:
    #    - binary_sensor.sensor
    #    - binary_sensor.sensor_2
    #    - binary_sensor.sensor_3
    #    - binary_sensor.sensor_4

#amcrest_nvr:
#  - name: NVR
#    host: !secret amcrest_url
#    username: !secret amcrest_user
#    password: !secret amcrest_pass
#    binary_sensors: [online]
#    sensors: [sdcard]
#    cameras:
#      - name: Front Porch
#        channel: 0
#        stream_source: rtsp
#        binary_sensors: [motion_detected]

#amcrest:
#  - host: !secret amcrest_host
#    username: !secret amcrest_user
#    password: !secret amcrest_password
#    binary_sensors: [audio_detected, online, motion_detected]

#camera:
#  - platform: ffmpeg
#    name: Doorbell RTSP Camera
#    input: !secret doorbell_camera_url
#  - platform: ffmpeg
#    name: Front RTSP Camera
#    input: !secret front_camera_url

#config:

#conversation:

default_config:

#device_tracker:

#discovery:

#ecobee:
#  api_key: !secret ecobee_api_key

#frontend:

#history:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_url

#logbook:

#logger:
#  default: info

#map:

# enable the mobile app support
#mobile_app:

notify:
  - name: doorbell_notify
    platform: group
    services:
      - service: alexa_media
        data:
          data:
            type: tts
          target:
            - media_player.kitchen_echo_show
  - name: laundry_notify
    platform: group
    services:
      - service: alexa_media
        data:
          data:
            type: tts
          target:
            - media_player.kitchen_echo_show
  - name: security_notify
    platform: group
    services:
      - service: mobile_app_moto_x4
        data:
          data:
            channel: security
            importance: max
      - service: mobile_app_iphone
        data:
          data:
            push:
              interruption-level: critical

#panel_iframe:
#  nodered:
#    title: "Node-Red"
#    icon: mdi:shuffle-variant
#    url: !secret nodered_url

#person:

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30

#script: !include scripts.yaml

#sensor:

#system_health:

#template:
#  - binary_sensor:
#      - name: Alexa Living Room Occupancy
#        unique_id: alexa_living_room_occupancy_motion
#        device_class: motion
#        state: "{{ states('input_boolean.alexa_living_room_occupancy') }}"

#tts:
#  - platform: google_translate
#    service_name: google_say

#updater:

#zeroconf:

#zone:

#zoneminder:
#  host: !secret zoneminder_url
#  username: admin
#  password: !secret zoneminder_pass
#  ssl: true
