homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: us_customary
  time_zone: America/New_York
  currency: USD
  country: US

default_config:

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
notify: !include groups.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_url

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 30

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_domains:
        - "light"
      include_entities:
        - "fan.living_room_fan"
        - "switch.front_porch_plugs"
        - "switch.printer_plug"
        - "switch.christmas_tree_plug"
        - "media_player.living_room_tv"
        - "media_player.shield_2"
      include_entity_globs:
        - "cover.*_shade"
        - "input_boolean.alexa_*_occupancy"
      exclude_entities:
        - "light.christmas_tree_plug_light"
        - "light.doorbell_led"
        # - "light.hatch_light"
        - "light.washer_plug_light"
        - "light.d3_led"
        - "light.d3_led_2"
        - "light.airgradient_open_air_status_led"
      exclude_entity_globs:
        - "light.*_follower"
        - "light.*_follower_*"

#amcrest_nvr:
#  - name: NVR
#    host: !secret amcrest_url
#    username: !secret amcrest_user
#    password: !secret amcrest_pass
#    binary_sensors: [online]
#    sensors: [sdcard]
#    cameras:
#      - name: Front Porch
#        channel: 0
#        stream_source: rtsp
#        binary_sensors: [motion_detected]

#amcrest:
#  - host: !secret amcrest_host
#    username: !secret amcrest_user
#    password: !secret amcrest_password
#    binary_sensors: [audio_detected, online, motion_detected]

#camera:
#  - platform: ffmpeg
#    name: Doorbell RTSP Camera
#    input: !secret doorbell_camera_url
#  - platform: ffmpeg
#    name: Front RTSP Camera
#    input: !secret front_camera_url

#panel_iframe:
#  nodered:
#    title: "Node-Red"
#    icon: mdi:shuffle-variant
#    url: !secret nodered_url

#template:
#  - binary_sensor:
#      - name: Alexa Living Room Occupancy
#        unique_id: alexa_living_room_occupancy_motion
#        device_class: motion
#        state: "{{ states('input_boolean.alexa_living_room_occupancy') }}"

#tts:
#  - platform: google_translate
#    service_name: google_say
