- alias: "[Fridge] Fridge Idle"
  id: fridge_idle
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_fridge_power
    below: '50'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.fridge_state
- alias: "[Fridge] Fridge Running"
  id: fridge_running
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_fridge_power
    above: '50'
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.fridge_state
- alias: "[Fridge] Basement Fridge Idle"
  id: basement_fridge_idle
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_fridge_power
    below: '50'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.basement_fridge_state
- alias: "[Fridge] Basement Fridge Running"
  id: basement_fridge_running
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_fridge_power
    above: '50'
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.basement_fridge_state
