- alias: "[Holiday] Turn on porch lights"
  id: holiday_porch_lights_on
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -6
  condition:
    condition: state
    entity_id: input_boolean.holiday
    state: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.front_porch_plugs
          - switch.outdoor_plug
- alias: "[Holiday] Turn off porch lights"
  id: holiday_porch_lights_off
  trigger:
    - platform: time
      at: "22:30:00"
  condition:
    condition: state
    entity_id: input_boolean.holiday
    state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.front_porch_plugs
          - switch.outdoor_plug
