- alias: "[Lighting] Motion activated entry"
  id: lighting_motion_entry
  use_blueprint:
    path: motion_brightness_light.yaml
    input:
      motion_entity: binary_sensor.entry_motion_occupancy
      brightness_entity: sensor.entry_motion_illuminance_lux
      brightness_trigger: 20
      no_motion_wait: 30
      light_target:
        entity_id: light.foyer_light
      light_brightness_night: 10
      light_brightness_day: 70
      time_night: "21:00:00"
      time_day: "07:00:00"
- alias: "[Lighting] Motion activated upstairs hall"
  id: lighting_motion_upstairs_hall
  use_blueprint:
    path: motion_brightness_light.yaml
    input:
      motion_entity: binary_sensor.upstairs_hall_motion_occupancy
      brightness_entity: sensor.upstairs_hall_motion_illuminance_lux
      brightness_trigger: 20
      no_motion_wait: 30
      light_target:
        entity_id: light.upstairs_hall_light
      light_brightness_night: 10
      light_brightness_day: 70
      time_night: "21:00:00"
      time_day: "07:00:00"
- alias: "[Lighting] Vacation schedule"
  id: lighting vacation
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 3
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 2
    - platform: time
      at: "22:30:00"
    - platform: time
      at: "23:30:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation
    state: "on"
  action:
    - if:
        - condition: trigger
          id: 0
      then:
        - service: light.turn_on
          target:
            entity_id: light.foyer_light
          data:
            brightness_pct: 60
    - if:
        - condition: trigger
          id: 1
      then:
        - service: light.turn_on
          target:
            entity_id: light.living_room_switch
          data:
            brightness_pct: 60
    - if:
        - condition: trigger
          id: 2
      then:
        - service: light.turn_off
          target:
            entity_id: light.living_room_switch
    - if:
        - condition: trigger
          id: 3
      then:
        - service: light.turn_off
          target:
            entity_id: light.foyer_light
