- alias: "[Lighting] Motion activated entry"
  id: lighting_motion_entry
  use_blueprint:
    path: motion_brightness_light.yaml
    input:
      motion_entity: binary_sensor.entry_motion_occupancy
      brightness_entity: sensor.entry_motion_illuminance_lux
      brightness_trigger: 20
      no_motion_wait: 30
      light_target:
        entity_id: light.foyer_light
      light_brightness_night: 10
      light_brightness_day: 70
      time_night: "21:00:00"
      time_day: "07:00:00"
- alias: "[Lighting] Motion activated upstairs hall"
  id: lighting_motion_upstairs_hall
  use_blueprint:
    path: motion_brightness_light.yaml
    input:
      motion_entity: binary_sensor.upstairs_hall_motion_occupancy
      brightness_entity: sensor.upstairs_hall_motion_illuminance_lux
      brightness_trigger: 20
      no_motion_wait: 30
      light_target:
        entity_id: light.upstairs_hall_light
      light_brightness_night: 10
      light_brightness_day: 70
      time_night: "21:00:00"
      time_day: "07:00:00"
- alias: "[Lighting] Master Bedroom Closet Left"
  id: master_closet_left
  use_blueprint:
    path: closet_light.yaml
    input:
      contact_entity: binary_sensor.master_bedroom_left_closet_contact_contact
      light_entity: switch.left_closet_light
      timeout: 10
- alias: "[Lighting] Master Bedroom Closet Right"
  id: master_closet_right
  use_blueprint:
    path: closet_light.yaml
    input:
      contact_entity: binary_sensor.master_bedroom_right_closet_contact_contact
      light_entity: switch.right_closet_light
      timeout: 10
- alias: "[Lighting] Basement Stair"
  id: lighting_basement_stair
  trigger:
    - type: state
      id: turn_on
      entity_id:
        - binary_sensor.basement_stair_contact_contact
        - binary_sensor.basement_stair_motion_occupancy
        - binary_sensor.basement_entry_motion_occupancy
      from: "off"
      to: "on"
    - type: state
      id: maybe_turn_off_short
      entity_id:
        - binary_sensor.basement_stair_contact_contact
        - binary_sensor.basement_stair_motion_occupancy
        - binary_sensor.basement_entry_motion_occupancy
      from: "on"
      to: "off"
    - type: state
      id: maybe_turn_off_long
      entity_id:
        - binary_sensor.basement_stair_motion_occupancy
        - binary_sensor.basement_entry_motion_occupancy
      from: "on"
      to: "off"
      for:
        minutes: 1
  condition:
    or:
      - and:
        - type: state
          state: "off"
          entity_id: switch.basement_stair_light
        - condition: trigger
          id: turn_on
      - and:
        - type: state
          state: "on"
          entity_id: switch.basement_stair_light
        - type: state
          state: "off"
          entity_id:
            - binary_sensor.basement_stair_contact_contact
            - binary_sensor.basement_entry_motion_occupancy
            - binary_sensor.basement_stair_motion_occupancy
      - and:
        - type: state
          state: "on"
          entity_id: switch.basement_stair_light
        - type: state
          state: "off"
          entity_id:
            - binary_sensor.basement_entry_motion_occupancy
            - binary_sensor.basement_stair_motion_occupancy
          for:
            minutes: 1
  action:
    - if:
        - condition: trigger
          id: turn_on
      then:
        - serivce: switch.turn_on
          target:
            entity_id: switch.basement_stair_light
      else:
        - serivce: switch.turn_off
          target:
            entity_id: switch.basement_stair_light
- alias: "[Lighting] Vacation schedule"
  id: lighting vacation
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 3
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 2
    - platform: time
      at: "22:30:00"
    - platform: time
      at: "23:30:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation
    state: "on"
  action:
    - if:
        - condition: trigger
          id: 0
      then:
        - service: light.turn_on
          target:
            entity_id: light.foyer_light
          data:
            brightness_pct: 60
    - if:
        - condition: trigger
          id: 1
      then:
        - service: light.turn_on
          target:
            entity_id: light.living_room_switch
          data:
            brightness_pct: 60
    - if:
        - condition: trigger
          id: 2
      then:
        - service: light.turn_off
          target:
            entity_id: light.living_room_switch
    - if:
        - condition: trigger
          id: 3
      then:
        - service: light.turn_off
          target:
            entity_id: light.foyer_light
