- alias: "[Thermostat] Set summer cooling temp"
  id: thermostate_summer_cool
  trigger:
    - platform: time
      at: "6:00:00"
    - platform: time
      at: "20:00:00"
    - platform: time
      at: "21:30:00"
    - platform: time
      at: "23:00:00"
    - platform: state
      entity_id: input_boolean.vacation
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.vacation
    state: "off"
  action:
    - choose:
      - conditions:
          - condition: time
            after: "6:00:00"
            before: "19:59:59"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: climate.thermostat
            data:
              target_temp_high: 76
              target_temp_low: 65
      - conditions:
          - condition: time
            after: "20:00:00"
            before: "21:29:59"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: climate.thermostat
            data:
              target_temp_high: 75
              target_temp_low: 65
      - conditions:
          - condition: time
            after: "21:30:00"
            before: "22:59:59"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: climate.thermostat
            data:
              target_temp_high: 74
              target_temp_low: 65
      - conditions:
          - condition: time
            after: "23:00:00"
            before: "5:59:59"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: climate.thermostat
            data:
              target_temp_high: 73
              target_temp_low: 65

- alias: "[Thermostat] Set vacation state"
  id: thermostate_vacation
  trigger:
    - platform: state
      entity_id: input_boolean.vacation
      to: "on"
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.thermostat
      data:
        target_temp_high: 80
        target_temp_low: 60
