- alias: "[TV] Set bias lights on TV power toggle"
  id: tv_bias_lighting
  trigger:
    platform: state
    entity_id: remote.sony_xbr_49x900e
    to:
      - "on"
      - "off"
  mode: queued
  condition:
    - or:
      - and:
        - "{{ is_state('switch.tv_backlight_plug', 'off') }}"
        - "{{ trigger.to_state.state == 'on' }}"
      - and:
        - "{{ is_state('switch.tv_backlight_plug', 'on') }}"
        - "{{ trigger.to_state.state == 'off' }}"
  action:
    - service: switch.toggle
      target:
        entity_id: switch.tv_backlight_plug
