- alias: "[TV] Set bias lights on TV power toggle"
  id: tv_bias_lighting
  trigger:
    platform: state
    entity_id: remote.sony_bravia_tv
    to:
      - "on"
      - "off"
  mode: queued
  action:
    - if:
        - "{{ states('switch.tv_backlight_plug') != trigger.to_state }}"
      then:
        - service: switch.toggle
          target:
            entity_id: switch.tv_backlight_plug
