- alias: Run Vacuum Upstairs
  id: vacuum_schedule_upstairs
  trigger:
    - platform: time
      at: '14:30'
  action:
    - choose:
        - conditions:
            - condition: time
              weekday: [mon, wed, fri]
          sequence:
            - service: script.vacuum_run_segments
              data:
                sequence_id:
                  entity_id: sensor.valetudo_tom_servo_map_segments
                room_names: ["Laundry", "Hallway", "Master Bedroom", "Master Bathroom"]
                vacuum_id:
                  entity_id: vacuum.valetudo_tom_servo
        - conditions:
            - condition: time
              weekday: [tue, thu]
          sequence:
            - service: script.vacuum_run_segments
              data:
                sequence_id:
                  entity_id: sensor.valetudo_tom_servo_map_segments
                room_names: ["Laundry", "Hallway", "Front Bedroom", "Back Bedroom", "Center Bedroom"]
                vacuum_id:
                  entity_id: vacuum.valetudo_tom_servo
