- alias: "[Vacuum] Check error state"
  id: vacuum_error_monitor
  trigger:
    platform: state
    entity_id:
      - vacuum.valetudo_crow
      - vacuum.valetudo_gypsy
      - vacuum.valetudo_tom_servo
    to: "error"
    for: "00:00:10"
  action:
    - service: persistent_notification.create
      data:
        title: "Vacuum Error"
        message: "Vacuum {{ trigger.entity_id }} has failed during cleaning"
- alias: "[Vacuum] Run Upstairs"
  id: vacuum_schedule_upstairs
  trigger:
    - platform: time
      at: '14:30'
  action:
    - choose:
        - conditions:
            - condition: time
              weekday: [mon, wed, fri]
          sequence:
            - service: script.vacuum_run_segments
              data:
                sequence_id:
                  entity_id: sensor.valetudo_tom_servo_map_segments
                room_names: ["Laundry", "Hallway", "Master Bedroom", "Master Bathroom"]
                vacuum_id: tom_servo
        - conditions:
            - condition: time
              weekday: [tue, thu]
          sequence:
            - service: script.vacuum_run_segments
              data:
                sequence_id:
                  entity_id: sensor.valetudo_tom_servo_map_segments
                room_names: ["Laundry", "Hallway", "Front Bedroom", "Back Bedroom", "Center Bedroom"]
                vacuum_id: tom_servo
- alias: "[Vacuum] Run Main Floor"
  id: vacuum_schedule_main
  trigger:
    - platform: time
      at: '2:00'
  action:
    - service: script.vacuum_run_segments
      data:
        sequence_id:
          entity_id: sensor.valetudo_crow_map_segments
        room_names: ["Office", "Bathroom", "Dining Room", "Kitchen"]
        vacuum_id: crow
- alias: "[Vacuum] Run Basement"
  id: vacuum_schedule_basement
  trigger:
    - platform: time
      at: '4:00'
  action:
    - service: script.vacuum_run_segments
      data:
        sequence_id:
          entity_id: sensor.valetudo_gypsy_map_segments
        room_names: ["Game Room", "Bathroom"]
        vacuum_id: gypsy
