- alias: "[Laundry] Washer Idle"
  id: laundry_washer_idle
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_plug_electric_consumption_w
    below: '10'
    for:
      minutes: 1
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.washing_machine_state
- alias: "[Laundry] Washer Running"
  id: laundry_washer_running
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_plug_electric_consumption_w
    above: '10'
    for:
      seconds: 30
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.washing_machine_state
- alias: "[Laundry] Dryer Idle"
  id: laundry_dryer_idle
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_plug_electric_consumption_w
    below: '10'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.dryer_state
- alias: "[Laundry] Dryer Running"
  id: laundry_dryer_running
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_plug_electric_consumption_w
    above: '10'
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.dryer_state
- alias: "[Laundry] Monitor state"
  id: laundry_monitor_state
  mode: restart
  trigger:
    - platform: state
      entity_id: input_boolean.washing_machine_state
      to: "on"
    - platform: state
      entity_id: input_boolean.dryer_state
      to: "on"
  action:
    - alias: Setup variables
      variables:
        washer_run: "{{ is_state('input_boolean.washing_machine_state', 'on') }}"
        dryer_run: "{{ is_state('input_boolean.dryer_state', 'on') }}"
    - alias: Wait for laundry to stop
      wait_template: "{{ is_state('input_boolean.washing_machine_state', 'off') and is_state('input_boolean.dryer_state', 'off') }}"
    - service: notify.laundry_notify
      data:
        message: >-
          {% if washer_run and dryer_run %}
          The washing machine and dryer are done
          {% elif washer_run %}
          The washing machine is done
          {% elif dryer_run %}
          The dryer is done
          {% else %}
          The laundry is done
          {% endif %}
