- alias: "[Laundry] Washer Idle"
  id: laundry_washer_idle
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_plug_electric_consumption_w
    below: '10'
    for:
      minutes: 1
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.washing_machine_state
- alias: "[Laundry] Washer Running"
  id: laundry_washer_running
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_plug_electric_consumption_w
    above: '10'
    for:
      seconds: 30
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.washing_machine_state
- alias: "[Laundry] Dryer Idle"
  id: laundry_dryer_idle
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_plug_electric_consumption_w
    below: '10'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.dryer_state
- alias: "[Laundry] Dryer Running"
  id: laundry_dryer_running
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_plug_electric_consumption_w
    above: '10'
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.dryer_state
- alias: "[Laundry] Monitor state"
  id: laundry_monitor_state
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: input_boolean.washing_machine_state
      to: "on"
    - platform: state
      entity_id: input_boolean.dryer_state
      to: "on"
  action:
    - alias: Repeat while laundry running
      repeat:
        while:
          condition: not
          conditions:
            condition: state
            entity_id:
              - input_boolean.washing_machine_state
              - input_boolean.dryer_state
            state: "off"
        sequence:
          - alias: Wait for state change
            wait_for_trigger:
              - platform: state
                entity_id: input_boolean.washing_machine_state
                to: ~
              - platform: state
                entity_id: input_boolean.dryer_state
                to: ~
    - service: notify.alexa_media_sean_s_echo_show
      data:
        message: The laundry is done
        data:
          type: tts
