name: Push updated NodeRed image
on:
  workflow_dispatch:
  push:
    paths:
      - 'nodered/**'
      - '.github/workflows/nodered_push.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'nodered/**'
      - '.github/workflows/nodered_push.yml'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          context: ./nodered
          file: ./nodered/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/nodered:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/nodered:latest
