name: Push updated RTL433 Autodiscovery image
on:
  workflow_dispatch:
  push:
    paths:
      - 'rtl_433_mqtt_hass/**'
      - '.github/workflows/rtl_433_mqtt_hass_push.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'rtl_433_mqtt_hass/**'
      - '.github/workflows/rtl_433_mqtt_hass_push.yaml'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          context: ./rtl_433_mqtt_hass
          file: ./rtl_433_mqtt_hass/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/rtl_433_mqtt_hass:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/rtl_433_mqtt_hass:latest
